################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application/User/Core \
Application/User/LIBJPEG/App \
Application/User/Startup \
Application/User/TouchGFX/App \
Application/User/TouchGFX/target \
Application/User/TouchGFX/target/generated \
Application/User/generated \
Application/User/gui \
Core/Src \
Drivers/BSP/Components/ft5336 \
Drivers/BSP/Components \
Drivers/BSP/Components/mx25lm51245g \
Drivers/BSP/Components/s70kl1281 \
Drivers/BSP/STM32H735G-DK \
Drivers/CMSIS \
Drivers/STM32H7xx_HAL_Driver/Src \
Drivers/STM32H7xx_HAL_Driver \
EWARM \
LIBJPEG/App \
MDK-ARM \
Middlewares/FreeRTOS \
Middlewares/LibJPEG \
Middlewares/ST/touchgfx/framework/source/platform/driver/touch \
Middlewares/ST/touchgfx/framework/source/platform/hal/simulator/sdl2 \
Middlewares/ST/touchgfx/framework/source/touchgfx/containers \
Middlewares/ST/touchgfx/framework/source/touchgfx/containers/clock \
Middlewares/ST/touchgfx/framework/source/touchgfx/containers/progress_indicators \
Middlewares/ST/touchgfx/framework/source/touchgfx/containers/scrollers \
Middlewares/ST/touchgfx/framework/source/touchgfx/widgets \
Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/canvas \
Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/graph \
Middlewares/ST/touchgfx/os \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/LibJPEG/source \
TouchGFX/App \
TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/screen1_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__generated \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src/video \
TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
TouchGFX/build/MINGW32_NT-6.2/gui/src/screen1_screen \
TouchGFX/build/MINGW32_NT-6.2/simulator \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/screen1_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/images/src/__generated \
TouchGFX/generated/simulator/src \
TouchGFX/generated/simulator/src/video \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/common \
TouchGFX/gui/src/model \
TouchGFX/gui/src/screen1_screen \
TouchGFX/simulator \
TouchGFX/target \
TouchGFX/target/generated \
gcc/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
gcc/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
gcc \

